(function () {
  "use strict";

  // ローマ字入力の対応表です。
  // 通常はここを触らず、出題単語だけ変えたい場合は下の words / bossWords を編集してください。
  const kanaMap = new Map(Object.entries({
      "あ": ["a"], "い": ["i", "yi"], "う": ["u", "wu"], "え": ["e"], "お": ["o"],
      "か": ["ka", "ca"], "き": ["ki"], "く": ["ku", "cu", "qu"], "け": ["ke"], "こ": ["ko", "co"],
      "さ": ["sa"], "し": ["shi", "si", "ci"], "す": ["su"], "せ": ["se", "ce"], "そ": ["so"],
      "た": ["ta"], "ち": ["chi", "ti"], "つ": ["tsu", "tu"], "て": ["te"], "と": ["to"],
      "な": ["na"], "に": ["ni"], "ぬ": ["nu"], "ね": ["ne"], "の": ["no"],
      "は": ["ha"], "ひ": ["hi"], "ふ": ["fu", "hu"], "へ": ["he"], "ほ": ["ho"],
      "ま": ["ma"], "み": ["mi"], "む": ["mu"], "め": ["me"], "も": ["mo"],
      "や": ["ya"], "ゆ": ["yu"], "よ": ["yo"],
      "ら": ["ra"], "り": ["ri"], "る": ["ru"], "れ": ["re"], "ろ": ["ro"],
      "わ": ["wa"], "を": ["wo"], "ん": ["n", "nn", "xn"],
      "が": ["ga"], "ぎ": ["gi"], "ぐ": ["gu"], "げ": ["ge"], "ご": ["go"],
      "ざ": ["za"], "じ": ["ji", "zi"], "ず": ["zu"], "ぜ": ["ze"], "ぞ": ["zo"],
      "だ": ["da"], "ぢ": ["ji", "di"], "づ": ["zu", "du"], "で": ["de"], "ど": ["do"],
      "ば": ["ba"], "び": ["bi"], "ぶ": ["bu"], "べ": ["be"], "ぼ": ["bo"],
      "ぱ": ["pa"], "ぴ": ["pi"], "ぷ": ["pu"], "ぺ": ["pe"], "ぽ": ["po"],
      "きゃ": ["kya"], "きぃ": ["kyi"], "きゅ": ["kyu"], "きぇ": ["kye"], "きょ": ["kyo"],
      "しゃ": ["sha", "sya"], "しぃ": ["syi"], "しゅ": ["shu", "syu"], "しぇ": ["she", "sye"], "しょ": ["sho", "syo"],
      "ちゃ": ["cha", "tya", "cya"], "ちぃ": ["tyi", "cyi"], "ちゅ": ["chu", "tyu", "cyu"], "ちぇ": ["che", "tye", "cye"], "ちょ": ["cho", "tyo", "cyo"],
      "にゃ": ["nya"], "にぃ": ["nyi"], "にゅ": ["nyu"], "にぇ": ["nye"], "にょ": ["nyo"],
      "ひゃ": ["hya"], "ひぃ": ["hyi"], "ひゅ": ["hyu"], "ひぇ": ["hye"], "ひょ": ["hyo"],
      "みゃ": ["mya"], "みぃ": ["myi"], "みゅ": ["myu"], "みぇ": ["mye"], "みょ": ["myo"],
      "りゃ": ["rya"], "りぃ": ["ryi"], "りゅ": ["ryu"], "りぇ": ["rye"], "りょ": ["ryo"],
      "ぎゃ": ["gya"], "ぎぃ": ["gyi"], "ぎゅ": ["gyu"], "ぎぇ": ["gye"], "ぎょ": ["gyo"],
      "じゃ": ["ja", "jya", "zya"], "じぃ": ["jyi", "zyi"], "じゅ": ["ju", "jyu", "zyu"], "じぇ": ["je", "jye", "zye"], "じょ": ["jo", "jyo", "zyo"],
      "びゃ": ["bya"], "びぃ": ["byi"], "びゅ": ["byu"], "びぇ": ["bye"], "びょ": ["byo"],
      "ぴゃ": ["pya"], "ぴぃ": ["pyi"], "ぴゅ": ["pyu"], "ぴぇ": ["pye"], "ぴょ": ["pyo"],
      "ふぁ": ["fa", "fwa"], "ふぃ": ["fi", "fwi"], "ふぇ": ["fe", "fwe"], "ふぉ": ["fo", "fwo"],
      "てぃ": ["thi", "tei"], "でぃ": ["dhi", "dei"], "とぅ": ["twu"], "どぅ": ["dwu"],
      "うぁ": ["wha"], "うぃ": ["wi", "whi"], "うぇ": ["we", "whe"], "うぉ": ["who"],
      "ぁ": ["la", "xa"], "ぃ": ["li", "xi"], "ぅ": ["lu", "xu"], "ぇ": ["le", "xe"], "ぉ": ["lo", "xo"],
      "ゃ": ["lya", "xya"], "ゅ": ["lyu", "xyu"], "ょ": ["lyo", "xyo"], "ゎ": ["lwa", "xwa"],
      "ー": ["-"], "、": [","], "。": ["."], "・": ["/"], " ": [" "]
    }));

  const smallKana = new Set(["ゃ", "ゅ", "ょ", "ぁ", "ぃ", "ぅ", "ぇ", "ぉ", "ゎ"]);

  // 通常敵に出す単語です。
  // text は画面表示、kana はローマ字判定に使う読み、rank は難易度です。
  const words = [
    // easy: 短く打ちやすい単語
    { text: "月", kana: "つき", rank: "easy" },
    { text: "星", kana: "ほし", rank: "easy" },
    { text: "宙", kana: "そら", rank: "easy" },
    { text: "宇宙", kana: "うちゅう", rank: "easy" },
    { text: "太陽", kana: "たいよう", rank: "easy" },
    { text: "地球", kana: "ちきゅう", rank: "easy" },
    { text: "火星", kana: "かせい", rank: "easy" },
    { text: "水星", kana: "すいせい", rank: "easy" },
    { text: "金星", kana: "きんせい", rank: "easy" },
    { text: "木星", kana: "もくせい", rank: "easy" },
    { text: "土星", kana: "どせい", rank: "easy" },
    { text: "天王星", kana: "てんのうせい", rank: "easy" },
    { text: "海王星", kana: "かいおうせい", rank: "easy" },
    { text: "流星", kana: "りゅうせい", rank: "easy" },
    { text: "星座", kana: "せいざ", rank: "easy" },
    { text: "銀河", kana: "ぎんが", rank: "easy" },
    { text: "彗星", kana: "すいせい", rank: "easy" },
    { text: "隕石", kana: "いんせき", rank: "easy" },
    { text: "夜空", kana: "よぞら", rank: "easy" },
    { text: "満月", kana: "まんげつ", rank: "easy" },
    { text: "新月", kana: "しんげつ", rank: "easy" },
    { text: "半月", kana: "はんげつ", rank: "easy" },
    { text: "星雲", kana: "せいうん", rank: "easy" },
    { text: "北斗", kana: "ほくと", rank: "easy" },
    { text: "南十字", kana: "みなみじゅうじ", rank: "easy" },
    { text: "天体", kana: "てんたい", rank: "easy" },
    { text: "宇宙港", kana: "うちゅうこう", rank: "easy" },
    { text: "船外", kana: "せんがい", rank: "easy" },
    { text: "星明かり", kana: "ほしあかり", rank: "easy" },
    { text: "月明かり", kana: "つきあかり", rank: "easy" },

    // normal: 宇宙用語・基本概念
    { text: "衛星", kana: "えいせい", rank: "normal" },
    { text: "重力", kana: "じゅうりょく", rank: "normal" },
    { text: "軌道", kana: "きどう", rank: "normal" },
    { text: "光年", kana: "こうねん", rank: "normal" },
    { text: "恒星", kana: "こうせい", rank: "normal" },
    { text: "惑星", kana: "わくせい", rank: "normal" },
    { text: "小惑星", kana: "しょうわくせい", rank: "normal" },
    { text: "人工衛星", kana: "じんこうえいせい", rank: "normal" },
    { text: "天の川", kana: "あまのがわ", rank: "normal" },
    { text: "月面", kana: "げつめん", rank: "normal" },
    { text: "宇宙船", kana: "うちゅうせん", rank: "normal" },
    { text: "宇宙服", kana: "うちゅうふく", rank: "normal" },
    { text: "無重力", kana: "むじゅうりょく", rank: "normal" },
    { text: "大気圏", kana: "たいきけん", rank: "normal" },
    { text: "流星群", kana: "りゅうせいぐん", rank: "normal" },
    { text: "日食", kana: "にっしょく", rank: "normal" },
    { text: "月食", kana: "げっしょく", rank: "normal" },
    { text: "太陽風", kana: "たいようふう", rank: "normal" },
    { text: "観測衛星", kana: "かんそくえいせい", rank: "normal" },
    { text: "宇宙飛行士", kana: "うちゅうひこうし", rank: "normal" },
    { text: "発射台", kana: "はっしゃだい", rank: "normal" },
    { text: "管制室", kana: "かんせいしつ", rank: "normal" },
    { text: "探査車", kana: "たんさしゃ", rank: "normal" },
    { text: "着陸船", kana: "ちゃくりくせん", rank: "normal" },
    { text: "補給船", kana: "ほきゅうせん", rank: "normal" },
    { text: "宇宙基地", kana: "うちゅうきち", rank: "normal" },
    { text: "星間雲", kana: "せいかんうん", rank: "normal" },
    { text: "電離層", kana: "でんりそう", rank: "normal" },
    { text: "放射線", kana: "ほうしゃせん", rank: "normal" },
    { text: "天体観測", kana: "てんたいかんそく", rank: "normal" },

    // hard: 長め・打ちごたえのある宇宙ワード
    { text: "スペースシャトル", kana: "すぺーすしゃとる", rank: "hard" },
    { text: "ブラックホール", kana: "ぶらっくほーる", rank: "hard" },
    { text: "宇宙ステーション", kana: "うちゅうすてーしょん", rank: "hard" },
    { text: "国際宇宙ステーション", kana: "こくさいうちゅうすてーしょん", rank: "hard" },
    { text: "ダークマター", kana: "だーくまたー", rank: "hard" },
    { text: "ダークエネルギー", kana: "だーくえねるぎー", rank: "hard" },
    { text: "ワームホール", kana: "わーむほーる", rank: "hard" },
    { text: "イベントホライズン", kana: "いべんとほらいずん", rank: "hard" },
    { text: "超新星爆発", kana: "ちょうしんせいばくはつ", rank: "hard" },
    { text: "惑星探査機", kana: "わくせいたんさき", rank: "hard" },
    { text: "宇宙望遠鏡", kana: "うちゅうぼうえんきょう", rank: "hard" },
    { text: "ロケットエンジン", kana: "ろけっとえんじん", rank: "hard" },
    { text: "銀河中心核", kana: "ぎんがちゅうしんかく", rank: "hard" },
    { text: "太陽系外惑星", kana: "たいようけいがいわくせい", rank: "hard" },
    { text: "電波望遠鏡", kana: "でんぱぼうえんきょう", rank: "hard" },
    { text: "宇宙エレベーター", kana: "うちゅうえれべーたー", rank: "hard" },
    { text: "小惑星探査", kana: "しょうわくせいたんさ", rank: "hard" },
    { text: "月面基地", kana: "げつめんきち", rank: "hard" },
    { text: "火星移住計画", kana: "かせいいじゅうけいかく", rank: "hard" },
    { text: "星間航行", kana: "せいかんこうこう", rank: "hard" },
    { text: "惑星間航行", kana: "わくせいかんこうこう", rank: "hard" },
    { text: "重力アシスト", kana: "じゅうりょくあしすと", rank: "hard" },
    { text: "太陽帆船", kana: "たいようはんせん", rank: "hard" },
    { text: "軌道エレベーター", kana: "きどうえれべーたー", rank: "hard" },
    { text: "恒星間通信", kana: "こうせいかんつうしん", rank: "hard" },
    { text: "月面ローバー", kana: "げつめんろーばー", rank: "hard" },
    { text: "宇宙放射線", kana: "うちゅうほうしゃせん", rank: "hard" },
    { text: "惑星防衛システム", kana: "わくせいぼうえいしすてむ", rank: "hard" },
    { text: "深宇宙探査", kana: "しんうちゅうたんさ", rank: "hard" },
    { text: "再突入カプセル", kana: "さいとつにゅうかぷせる", rank: "hard" },

    // rare: 星名・銀河名・探査機名など
    { text: "ベテルギウス", kana: "べてるぎうす", rank: "rare" },
    { text: "アルデバラン", kana: "あるでばらん", rank: "rare" },
    { text: "アンドロメダ銀河", kana: "あんどろめだぎんが", rank: "rare" },
    { text: "プロキシマケンタウリ", kana: "ぷろきしまけんたうり", rank: "rare" },
    { text: "シリウス", kana: "しりうす", rank: "rare" },
    { text: "カノープス", kana: "かのーぷす", rank: "rare" },
    { text: "アンタレス", kana: "あんたれす", rank: "rare" },
    { text: "リゲル", kana: "りげる", rank: "rare" },
    { text: "デネブ", kana: "でねぶ", rank: "rare" },
    { text: "アルタイル", kana: "あるたいる", rank: "rare" },
    { text: "ベガ", kana: "べが", rank: "rare" },
    { text: "カッシーニ", kana: "かっしーに", rank: "rare" },
    { text: "ボイジャー", kana: "ぼいじゃー", rank: "rare" },
    { text: "はやぶさ", kana: "はやぶさ", rank: "rare" },
    { text: "はやぶさ2", kana: "はやぶさつー", rank: "rare" },
    { text: "あかつき", kana: "あかつき", rank: "rare" },
    { text: "ひてん", kana: "ひてん", rank: "rare" },
    { text: "のぞみ", kana: "のぞみ", rank: "rare" },
    { text: "ジュノー", kana: "じゅのー", rank: "rare" },
    { text: "ニュー・ホライズンズ", kana: "にゅー・ほらいずんず", rank: "rare" },
    { text: "ジェイムズウェッブ宇宙望遠鏡", kana: "じぇいむずうぇっぶうちゅうぼうえんきょう", rank: "rare" },
    { text: "ハッブル宇宙望遠鏡", kana: "はっぶるうちゅうぼうえんきょう", rank: "rare" },
    { text: "オリオン大星雲", kana: "おりおんだいせいうん", rank: "rare" },
    { text: "プレアデス星団", kana: "ぷれあですせいだん", rank: "rare" },
    { text: "マゼラン雲", kana: "まぜらんうん", rank: "rare" },
    { text: "ケンタウルス座アルファ星", kana: "けんたうるすざあるふぁせい", rank: "rare" },
    { text: "トラピストワン", kana: "とらぴすとわん", rank: "rare" },
    { text: "オウムアムア", kana: "おうむあむあ", rank: "rare" },
    { text: "チャンドラX線観測衛星", kana: "ちゃんどらえっくすせんかんそくえいせい", rank: "rare" },
    { text: "スピッツァー宇宙望遠鏡", kana: "すぴっつぁーうちゅうぼうえんきょう", rank: "rare" },
    { text: "ガリレオ探査機", kana: "がりれおたんさき", rank: "rare" },
    { text: "パーカーソーラープローブ", kana: "ぱーかーそーらーぷろーぶ", rank: "rare" },
    { text: "ロゼッタ探査機", kana: "ろぜったたんさき", rank: "rare" },
    { text: "イータカリーナ星雲", kana: "いーたかりーなせいうん", rank: "rare" },
    { text: "いて座Aスター", kana: "いてざえーすたー", rank: "rare" }
  ];

  // ボスに出す長文です。
  // text は画面表示、kana は入力判定用の読み、ruby はふりがな表示に使います。
  const bossWords = [
    { text: "月面に着陸せよ", kana: "げつめんにちゃくりくせよ", rank: "boss", ruby: [["月面に着陸せよ", "げつめんにちゃくりくせよ"]] },
    { text: "軌道を修正せよ", kana: "きどうをしゅうせいせよ", rank: "boss", ruby: [["軌道を修正せよ", "きどうをしゅうせいせよ"]] },
    { text: "燃料を節約せよ", kana: "ねんりょうをせつやくせよ", rank: "boss", ruby: [["燃料を節約せよ", "ねんりょうをせつやくせよ"]] },
    { text: "通信を回復せよ", kana: "つうしんをかいふくせよ", rank: "boss", ruby: [["通信を回復せよ", "つうしんをかいふくせよ"]] },
    { text: "隕石を回避せよ", kana: "いんせきをかいひせよ", rank: "boss", ruby: [["隕石を回避せよ", "いんせきをかいひせよ"]] },
    { text: "重力圏を離脱せよ", kana: "じゅうりょくけんをりだつせよ", rank: "boss", ruby: [["重力圏を離脱せよ", "じゅうりょくけんをりだつせよ"]] },
    { text: "太陽風を観測せよ", kana: "たいようふうをかんそくせよ", rank: "boss", ruby: [["太陽風を観測せよ", "たいようふうをかんそくせよ"]] },
    { text: "銀河の中心へ向かえ", kana: "ぎんがのちゅうしんへむかえ", rank: "boss", ruby: [["銀河の中心へ向かえ", "ぎんがのちゅうしんへむかえ"]] },
    { text: "ブラックホールを避けろ", kana: "ぶらっくほーるをさけろ", rank: "boss", ruby: [["ブラックホールを避けろ", "ぶらっくほーるをさけろ"]] },
    { text: "宇宙船を発進せよ", kana: "うちゅうせんをはっしんせよ", rank: "boss", ruby: [["宇宙船を発進せよ", "うちゅうせんをはっしんせよ"]] },
    { text: "未知の星を調査せよ", kana: "みちのほしをちょうさせよ", rank: "boss", ruby: [["未知の星を調査せよ", "みちのほしをちょうさせよ"]] },
    { text: "酸素残量を確認せよ", kana: "さんそざんりょうをかくにんせよ", rank: "boss", ruby: [["酸素残量を確認せよ", "さんそざんりょうをかくにんせよ"]] },
    { text: "探査機を帰還させろ", kana: "たんさきをきかんさせろ", rank: "boss", ruby: [["探査機を帰還させろ", "たんさきをきかんさせろ"]] },
    { text: "星間航路を確保せよ", kana: "せいかんこうろをかくほせよ", rank: "boss", ruby: [["星間航路を確保せよ", "せいかんこうろをかくほせよ"]] },
    { text: "最終シーケンスを起動せよ", kana: "さいしゅうしーけんすをきどうせよ", rank: "boss", ruby: [["最終シーケンスを起動せよ", "さいしゅうしーけんすをきどうせよ"]] }
  ];

  window.CosmoKanaBlasterData = {
    kanaMap,
    smallKana,
    words,
    bossWords
  };
}());
